---
schema:
  attributes:     # Optional attributes that can be used on any key
    implied:        # Value or func; return not overridable
    suggested:      # Value or func; return overridable
                        # BUILT IN FUNCTIONS FOR IMPLIED, SUGGESTED
                          # generate_sequential_ints
                          # generate_hash
                        # USE YOUR OWN
    mutable:        # Bool; Value can be changed
    optional:       # Bool; Value can be null
    default:        # Value or func
  all:            # Keys that will automatically be on each model
    - hash:
        id:         # A UUID value found on all models
          implied: generate_hash
  keys:           # Special key types with special behavior
    string:         # If not str, attempt cast to str
      encoding:       # Specify string encoding
        optional: True
        default: utf-8
    hash:         # A hash value
    integer:      # If not int, attempt cast to int
    list:         # A list of values, must be initialized with key type
    boolean:      # A True/False
    map:          # A key/value map, must be initialized with key type
    model:        # Reference to another model
      name:         # Which model?
        optional: True # If false it will use the top-level key name as model.Name

# First load model (no s) file with structure
  # Strictly yamllint
  # Check that each key is in schema.keys
    # Check that each attribute is in schema.attributes
    # Create object for each key
      # set attributes, enforcing rules as we go, excepting as needed
  # Model is ready for data
# Load models (with s) file with data
  # Check that data contains single top level key
  # Check that key is valid model
  # Select model